/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Klopp
 */
public class CheckoutScreen extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutScreen
     */
    public CheckoutScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CheckoutTextArea = new javax.swing.JTextArea();
        AddProductsButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CheckoutConfirmCheckBox = new javax.swing.JCheckBox();
        CheckoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Checkout:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 370, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(null);

        CheckoutTextArea.setColumns(20);
        CheckoutTextArea.setRows(5);
        jScrollPane1.setViewportView(CheckoutTextArea);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 1030, 290);

        AddProductsButton.setBackground(new java.awt.Color(0, 255, 255));
        AddProductsButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddProductsButton.setForeground(new java.awt.Color(0, 51, 255));
        AddProductsButton.setText("Add products");
        AddProductsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductsButtonMouseClicked(evt);
            }
        });
        jPanel2.add(AddProductsButton);
        AddProductsButton.setBounds(470, 320, 170, 30);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(null);

        CheckoutConfirmCheckBox.setBackground(new java.awt.Color(0, 153, 255));
        CheckoutConfirmCheckBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CheckoutConfirmCheckBox.setText("Confirm Checkout?");
        jPanel3.add(CheckoutConfirmCheckBox);
        CheckoutConfirmCheckBox.setBounds(470, 10, 170, 25);

        CheckoutButton.setBackground(new java.awt.Color(0, 255, 255));
        CheckoutButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CheckoutButton.setForeground(new java.awt.Color(0, 51, 255));
        CheckoutButton.setText("Checkout");
        CheckoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutButtonMouseClicked(evt);
            }
        });
        jPanel3.add(CheckoutButton);
        CheckoutButton.setBounds(480, 50, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProductsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductsButtonMouseClicked
        MainScreen scrn = new MainScreen();
        this.CheckoutTextArea.setLineWrap(true);
        this.CheckoutTextArea.setText(scrn.BuyButtonMouseClicked(evt));
        
        
        
    }//GEN-LAST:event_AddProductsButtonMouseClicked

    private void CheckoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckoutScreen scr = new CheckoutScreen();
                scr.setVisible(true);
                scr.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductsButton;
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JCheckBox CheckoutConfirmCheckBox;
    private javax.swing.JTextArea CheckoutTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
