//Gerhard Kloppers
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Klopp
 */
public class CreateAccountLogMeIn extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountLogMeIn
     */
    public CreateAccountLogMeIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AccCreatePassword = new javax.swing.JPasswordField();
        AccCreatePassConfirm = new javax.swing.JPasswordField();
        AccCreateUsername = new javax.swing.JTextField();
        AccCreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Create an account:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 340, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 110, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 170, 93, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 240, 170, 30);

        AccCreatePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccCreatePasswordKeyPressed(evt);
            }
        });
        jPanel2.add(AccCreatePassword);
        AccCreatePassword.setBounds(280, 170, 280, 30);

        AccCreatePassConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccCreatePassConfirmKeyPressed(evt);
            }
        });
        jPanel2.add(AccCreatePassConfirm);
        AccCreatePassConfirm.setBounds(280, 230, 280, 30);

        AccCreateUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccCreateUsernameKeyPressed(evt);
            }
        });
        jPanel2.add(AccCreateUsername);
        AccCreateUsername.setBounds(280, 110, 280, 30);

        AccCreateButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccCreateButton.setText("Create Account");
        AccCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccCreateButtonMouseClicked(evt);
            }
        });
        AccCreateButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccCreateButtonKeyPressed(evt);
            }
        });
        jPanel2.add(AccCreateButton);
        AccCreateButton.setBounds(210, 340, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccCreateButtonMouseClicked
        CreateAccountLogMeIn Acc = new CreateAccountLogMeIn();
        String UserName = AccCreateUsername.getText();
        String Password = new String(AccCreatePassword.getPassword());
        String PassConfirm = new String(AccCreatePassConfirm.getPassword());
        boolean found = false;
        boolean confirmPassword = false;
        if (this.AccCreateUsername.getText().isEmpty() || this.AccCreatePassword.getPassword().length == 0 || this.AccCreatePassConfirm.getPassword().length == 0){
            JOptionPane.showMessageDialog(rootPane, "Please fill in the required fields!");
            return;
        }
        try {
            if (Password.compareTo(PassConfirm) == 0) {
                try (FileWriter fw = new FileWriter("LoginDetails.txt", true)) {
                    fw.write(UserName + "#" + Password + "\n");
                    found = true;
                    confirmPassword = true;
                }
            }
            if (confirmPassword == false){
                JOptionPane.showMessageDialog(rootPane, "Confirm password does not match!");
                this.AccCreatePassConfirm.setText("");
                return;
            }
            if (found && confirmPassword) {
                JOptionPane.showMessageDialog(rootPane, "You have succesfully created an account!");
                Acc.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "Please login again.");
                LogMeInForm login = new LogMeInForm();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
                this.dispose();
            }

        } catch (IOException ex) {
            Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AccCreateButtonMouseClicked

    private void AccCreateButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccCreateButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CreateAccountLogMeIn Acc = new CreateAccountLogMeIn();
        String UserName = AccCreateUsername.getText();
        String Password = new String(AccCreatePassword.getPassword());
        String PassConfirm = new String(AccCreatePassConfirm.getPassword());
        boolean found = false;
        boolean confirmPassword = false;
        if (this.AccCreateUsername.getText().isEmpty() || this.AccCreatePassword.getPassword().length == 0 || this.AccCreatePassConfirm.getPassword().length == 0){
            JOptionPane.showMessageDialog(rootPane, "Please fill in the required fields!");
            return;
        }
        try {
            if (Password.compareTo(PassConfirm) == 0) {
                try (FileWriter fw = new FileWriter("LoginDetails.txt", true)) {
                    fw.write(UserName + "#" + Password + "\n");
                    found = true;
                    confirmPassword = true;
                }
            }
            if (confirmPassword == false){
                JOptionPane.showMessageDialog(rootPane, "Confirm password does not match!");
                this.AccCreatePassConfirm.setText("");
                return;
            }
            if (found && confirmPassword) {
                JOptionPane.showMessageDialog(rootPane, "You have succesfully created an account!");
                Acc.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "Please login again.");
                LogMeInForm login = new LogMeInForm();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
                this.dispose();
            }

        } catch (IOException ex) {
            Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_AccCreateButtonKeyPressed

    private void AccCreatePassConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccCreatePassConfirmKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CreateAccountLogMeIn Acc = new CreateAccountLogMeIn();
        String UserName = AccCreateUsername.getText();
        String Password = new String(AccCreatePassword.getPassword());
        String PassConfirm = new String(AccCreatePassConfirm.getPassword());
        boolean found = false;
        boolean confirmPassword = false;
        if (this.AccCreateUsername.getText().isEmpty() || this.AccCreatePassword.getPassword().length == 0 || this.AccCreatePassConfirm.getPassword().length == 0){
            JOptionPane.showMessageDialog(rootPane, "Please fill in the required fields!");
            return;
        }
        try {
            if (Password.compareTo(PassConfirm) == 0) {
                try (FileWriter fw = new FileWriter("LoginDetails.txt", true)) {
                    fw.write(UserName + "#" + Password + "\n");
                    found = true;
                    confirmPassword = true;
                }
            }
            if (confirmPassword == false){
                JOptionPane.showMessageDialog(rootPane, "Confirm password does not match!");
                this.AccCreatePassConfirm.setText("");
                return;
            }
            if (found && confirmPassword) {
                JOptionPane.showMessageDialog(rootPane, "You have succesfully created an account!");
                Acc.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "Please login again.");
                LogMeInForm login = new LogMeInForm();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
                this.dispose();
            }

        } catch (IOException ex) {
            Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
           JOptionPane.showMessageDialog(rootPane, "• This is the Account creation screen.\n• Please enter you Username.\n• Please enter your password and confirm that password.");
        }
    }//GEN-LAST:event_AccCreatePassConfirmKeyPressed

    private void AccCreateUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccCreateUsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
           JOptionPane.showMessageDialog(rootPane, "• This is the Account creation screen.\n• Please enter you Username.\n• Please enter your password and confirm that password");
        }
    }//GEN-LAST:event_AccCreateUsernameKeyPressed

    private void AccCreatePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccCreatePasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
           JOptionPane.showMessageDialog(rootPane, "• This is the Account creation screen.\n• Please enter you Username.\n• Please enter your password and confirm that password");
        }
    }//GEN-LAST:event_AccCreatePasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLogMeIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateAccountLogMeIn acc = new CreateAccountLogMeIn();
                acc.setVisible(true);
                acc.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccCreateButton;
    private javax.swing.JPasswordField AccCreatePassConfirm;
    private javax.swing.JPasswordField AccCreatePassword;
    private javax.swing.JTextField AccCreateUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
