package View;

;

import Controller.Shopping;
import java.util.HashSet;
import javax.swing.ImageIcon;
import Model.Products;
import Model.Books;
import Model.DigitalItems;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Klopp
 */
public class MainScreen extends javax.swing.JFrame{

    Shopping MyShop = new Shopping();
    
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        DgitalItemsTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ProductPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProductButton1 = new javax.swing.JButton();
        ProductPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ProductButton2 = new javax.swing.JButton();
        ProductPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ProductButton3 = new javax.swing.JButton();
        ProductPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ProductButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BookPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BookButton1 = new javax.swing.JButton();
        BookPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BookButton2 = new javax.swing.JButton();
        BookPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BookButton3 = new javax.swing.JButton();
        BookPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BookButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        DigitalItemPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        DigitalItemButton1 = new javax.swing.JButton();
        DigitalItemPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DigitalItemButton2 = new javax.swing.JButton();
        DigitalItemPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DigitalItemButton3 = new javax.swing.JButton();
        DigitalItemPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DigitalItemButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        InternalScrollPane = new javax.swing.JScrollPane();
        InternalProductText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));

        DgitalItemsTab.setBackground(new java.awt.Color(0, 153, 255));
        DgitalItemsTab.setBorder(new javax.swing.border.MatteBorder(null));
        DgitalItemsTab.setForeground(new java.awt.Color(0, 153, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));

        ProductPanel1.setBackground(new java.awt.Color(255, 255, 255));
        ProductPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Shovel.png"))); // NOI18N
        ProductPanel1.add(jLabel2);
        jLabel2.setBounds(70, 50, 110, 113);

        ProductButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButton1MouseClicked(evt);
            }
        });
        ProductButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductButton1ActionPerformed(evt);
            }
        });
        ProductPanel1.add(ProductButton1);
        ProductButton1.setBounds(0, 0, 240, 210);

        ProductPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toilet.png"))); // NOI18N
        ProductPanel2.add(jLabel3);
        jLabel3.setBounds(70, 50, 113, 110);

        ProductButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButton2MouseClicked(evt);
            }
        });
        ProductPanel2.add(ProductButton2);
        ProductButton2.setBounds(0, 0, 240, 210);

        ProductPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Hanger.png"))); // NOI18N
        ProductPanel3.add(jLabel4);
        jLabel4.setBounds(70, 50, 113, 100);

        ProductButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButton3MouseClicked(evt);
            }
        });
        ProductPanel3.add(ProductButton3);
        ProductButton3.setBounds(0, 0, 240, 210);

        ProductPanel4.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\Shoes.png")); // NOI18N
        ProductPanel4.add(jLabel5);
        jLabel5.setBounds(60, 40, 120, 120);

        ProductButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButton4MouseClicked(evt);
            }
        });
        ProductPanel4.add(ProductButton4);
        ProductButton4.setBounds(0, 0, 240, 210);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ProductPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        DgitalItemsTab.addTab("Products", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        BookPanel1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\WoomenInTheWindow.jpg")); // NOI18N
        BookPanel1.add(jLabel6);
        jLabel6.setBounds(60, 10, 130, 190);

        BookButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookButton1MouseClicked(evt);
            }
        });
        BookPanel1.add(BookButton1);
        BookButton1.setBounds(0, 0, 240, 220);

        BookPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\BehindBlueEyes.jpg")); // NOI18N
        BookPanel2.add(jLabel7);
        jLabel7.setBounds(50, 10, 140, 190);

        BookButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookButton2MouseClicked(evt);
            }
        });
        BookPanel2.add(BookButton2);
        BookButton2.setBounds(0, 0, 240, 220);

        BookPanel3.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\Spud.jpg")); // NOI18N
        BookPanel3.add(jLabel8);
        jLabel8.setBounds(60, 10, 130, 190);

        BookButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookButton3MouseClicked(evt);
            }
        });
        BookPanel3.add(BookButton3);
        BookButton3.setBounds(0, 0, 240, 220);

        BookPanel4.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\diary-of-a-wimpy-kid.jpg")); // NOI18N
        BookPanel4.add(jLabel9);
        jLabel9.setBounds(60, 10, 130, 190);

        BookButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookButton4MouseClicked(evt);
            }
        });
        BookPanel4.add(BookButton4);
        BookButton4.setBounds(0, 0, 240, 220);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(BookPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BookPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap())
        );

        DgitalItemsTab.addTab("Books", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        DigitalItemPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\ButterflyKnifeSlaugter.png")); // NOI18N
        DigitalItemPanel1.add(jLabel10);
        jLabel10.setBounds(20, 20, 200, 150);

        DigitalItemButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DigitalItemButton1MouseClicked(evt);
            }
        });
        DigitalItemPanel1.add(DigitalItemButton1);
        DigitalItemButton1.setBounds(0, 0, 240, 210);

        DigitalItemPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\AK47uAlienred.png")); // NOI18N
        DigitalItemPanel2.add(jLabel11);
        jLabel11.setBounds(40, 20, 160, 150);

        DigitalItemButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DigitalItemButton2MouseClicked(evt);
            }
        });
        DigitalItemPanel2.add(DigitalItemButton2);
        DigitalItemButton2.setBounds(0, 0, 240, 210);

        DigitalItemPanel3.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\KarambitFade.png")); // NOI18N
        DigitalItemPanel3.add(jLabel12);
        jLabel12.setBounds(50, 40, 150, 120);

        DigitalItemButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DigitalItemButton3MouseDragged(evt);
            }
        });
        DigitalItemPanel3.add(DigitalItemButton3);
        DigitalItemButton3.setBounds(0, 0, 240, 210);

        DigitalItemPanel4.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Klopp\\OneDrive\\Desktop\\PAT .png's\\TemperedMetalFacemask.png")); // NOI18N
        DigitalItemPanel4.add(jLabel13);
        jLabel13.setBounds(50, 40, 140, 120);

        DigitalItemButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DigitalItemButton4MouseClicked(evt);
            }
        });
        DigitalItemPanel4.add(DigitalItemButton4);
        DigitalItemButton4.setBounds(0, 0, 240, 210);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(DigitalItemPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DigitalItemPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DigitalItemPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DigitalItemPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DigitalItemPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DigitalItemPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DigitalItemPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(DigitalItemPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        DgitalItemsTab.addTab("Digital items", jPanel3);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Product Page:");

        jInternalFrame1.setVisible(true);

        InternalProductText.setColumns(20);
        InternalProductText.setRows(5);
        InternalScrollPane.setViewportView(InternalProductText);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InternalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InternalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Buy");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(DgitalItemsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DgitalItemsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void ProductButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButton1MouseClicked
                int productNum = 0;
                Font font = new Font("Arial", Font.BOLD, 20);
                Products p = this.MyShop.ShoppingProducts().get(productNum);
                String txt = "Product ID: " + p.getProductID() + System.lineSeparator() + "\n" + "Product name: " + p.getProductName() + System.lineSeparator() + "\n" + "Product price: R" + p.getProductPrice() + System.lineSeparator() + "\n" + "Product description: " + p.getProductDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
                
                
    }//GEN-LAST:event_ProductButton1MouseClicked

    private void ProductButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductButton1ActionPerformed

    private void ProductButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButton2MouseClicked
                int productNum = 1;
                Font font = new Font("Arial", Font.BOLD, 20);
                Products p = this.MyShop.ShoppingProducts().get(productNum);
                String txt = "Product ID: " + p.getProductID() + System.lineSeparator() + "\n" + "Product name: " + p.getProductName() + System.lineSeparator() + "\n" + "Product price: R" + p.getProductPrice() + System.lineSeparator() + "\n" + "Product description: " + p.getProductDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
                
    }//GEN-LAST:event_ProductButton2MouseClicked

    private void ProductButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButton3MouseClicked
                int productNum = 2;
                Font font = new Font("Arial", Font.BOLD, 20);
                Products p = this.MyShop.ShoppingProducts().get(productNum);
                String txt = "Product ID: " + p.getProductID() + System.lineSeparator() + "\n" + "Product name: " + p.getProductName() + System.lineSeparator() + "\n" + "Product price: R" + p.getProductPrice() + System.lineSeparator() + "\n" + "Product description: " + p.getProductDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_ProductButton3MouseClicked

    private void ProductButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButton4MouseClicked
                int productNum = 3;
                Font font = new Font("Arial", Font.BOLD, 20);
                Products p = this.MyShop.ShoppingProducts().get(productNum);
                String txt = "Product ID: " + p.getProductID() + System.lineSeparator() + "\n" + "Product name: " + p.getProductName() + System.lineSeparator() + "\n" + "Product price: R" + p.getProductPrice() + System.lineSeparator() + "\n" + "Product description: " + p.getProductDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_ProductButton4MouseClicked

    private void BookButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookButton1MouseClicked
           int bookNum = 0;
                Font font = new Font("Arial", Font.BOLD, 20);
                Books p = this.MyShop.ShoppingBooks().get(bookNum);
                String txt = "Book ID: " + p.getBookID() + System.lineSeparator() + "\n" + "Book name: " + p.getBookName() + System.lineSeparator() + "\n" + "Book price: R" + p.getBookPrice() + System.lineSeparator() + "\n" + "Book description: " + p.getBookDiscription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_BookButton1MouseClicked

    private void BookButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookButton2MouseClicked
        int bookNum = 1;
                Font font = new Font("Arial", Font.BOLD, 20);
                Books p = this.MyShop.ShoppingBooks().get(bookNum);
                String txt = "Book ID: " + p.getBookID() + System.lineSeparator() + "\n" + "Book name: " + p.getBookName() + System.lineSeparator() + "\n" + "Book price: R" + p.getBookPrice() + System.lineSeparator() + "\n" + "Book description: " + p.getBookDiscription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_BookButton2MouseClicked

    private void BookButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookButton3MouseClicked
        int bookNum = 2;
                Font font = new Font("Arial", Font.BOLD, 20);
                Books p = this.MyShop.ShoppingBooks().get(bookNum);
                String txt = "Book ID: " + p.getBookID() + System.lineSeparator() + "\n" + "Book name: " + p.getBookName() + System.lineSeparator() + "\n" + "Book price: R" + p.getBookPrice() + System.lineSeparator() + "\n" + "Book description: " + p.getBookDiscription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_BookButton3MouseClicked

    private void BookButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookButton4MouseClicked
        int bookNum = 3;
                Font font = new Font("Arial", Font.BOLD, 20);
                Books p = this.MyShop.ShoppingBooks().get(bookNum);
                String txt = "Book ID: " + p.getBookID() + System.lineSeparator() + "\n" + "Book name: " + p.getBookName() + System.lineSeparator() + "\n" + "Book price: R" + p.getBookPrice() + System.lineSeparator() + "\n" + "Book description: " + p.getBookDiscription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_BookButton4MouseClicked

    private void DigitalItemButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DigitalItemButton1MouseClicked
        int digitalitemNum = 0;
                Font font = new Font("Arial", Font.BOLD, 20);
                DigitalItems p = this.MyShop.ShoppingDigitalItems().get(digitalitemNum);
                String txt = "Digital Item ID: " + p.getDigitalItemID() + System.lineSeparator() + "\n" + "Digital Item name: " + p.getDigitalItemName() + System.lineSeparator() + "\n" + "Digital Item price: R" + p.getDigitalItemPrice() + System.lineSeparator() + "\n" + "Digital Item description: " + p.getDigitalItemDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_DigitalItemButton1MouseClicked

    private void DigitalItemButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DigitalItemButton2MouseClicked
        int digitalitemNum = 1;
                Font font = new Font("Arial", Font.BOLD, 20);
                DigitalItems p = this.MyShop.ShoppingDigitalItems().get(digitalitemNum);
                String txt = "Digital Item ID: " + p.getDigitalItemID() + System.lineSeparator() + "\n" + "Digital Item name: " + p.getDigitalItemName() + System.lineSeparator() + "\n" + "Digital Item price: R" + p.getDigitalItemPrice() + System.lineSeparator() + "\n" + "Digital Item description: " + p.getDigitalItemDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_DigitalItemButton2MouseClicked

    private void DigitalItemButton3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DigitalItemButton3MouseDragged
        int digitalitemNum = 2;
                Font font = new Font("Arial", Font.BOLD, 20);
                DigitalItems p = this.MyShop.ShoppingDigitalItems().get(digitalitemNum);
                String txt = "Digital Item ID: " + p.getDigitalItemID() + System.lineSeparator() + "\n" + "Digital Item name: " + p.getDigitalItemName() + System.lineSeparator() + "\n" + "Digital Item price: R" + p.getDigitalItemPrice() + System.lineSeparator() + "\n" + "Digital Item description: " + p.getDigitalItemDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_DigitalItemButton3MouseDragged

    private void DigitalItemButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DigitalItemButton4MouseClicked
        int digitalitemNum = 3;
                Font font = new Font("Arial", Font.BOLD, 20);
                DigitalItems p = this.MyShop.ShoppingDigitalItems().get(digitalitemNum);
                String txt = "Digital Item ID: " + p.getDigitalItemID() + System.lineSeparator() + "\n" + "Digital Item name: " + p.getDigitalItemName() + System.lineSeparator() + "\n" + "Digital Item price: R" + p.getDigitalItemPrice() + System.lineSeparator() + "\n" + "Digital Item description: " + p.getDigitalItemDescription();
                this.InternalProductText.setFont(font);
                this.InternalProductText.setLineWrap(true);
                this.InternalProductText.setText(txt);
    }//GEN-LAST:event_DigitalItemButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        CheckoutScreen scrn = new CheckoutScreen();
        scrn.setVisible(true);
        scrn.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton1;
    private javax.swing.JButton BookButton2;
    private javax.swing.JButton BookButton3;
    private javax.swing.JButton BookButton4;
    private javax.swing.JPanel BookPanel1;
    private javax.swing.JPanel BookPanel2;
    private javax.swing.JPanel BookPanel3;
    private javax.swing.JPanel BookPanel4;
    private javax.swing.JTabbedPane DgitalItemsTab;
    private javax.swing.JButton DigitalItemButton1;
    private javax.swing.JButton DigitalItemButton2;
    private javax.swing.JButton DigitalItemButton3;
    private javax.swing.JButton DigitalItemButton4;
    private javax.swing.JPanel DigitalItemPanel1;
    private javax.swing.JPanel DigitalItemPanel2;
    private javax.swing.JPanel DigitalItemPanel3;
    private javax.swing.JPanel DigitalItemPanel4;
    private javax.swing.JTextArea InternalProductText;
    private javax.swing.JScrollPane InternalScrollPane;
    private javax.swing.JButton ProductButton1;
    private javax.swing.JButton ProductButton2;
    private javax.swing.JButton ProductButton3;
    private javax.swing.JButton ProductButton4;
    private javax.swing.JPanel ProductPanel1;
    private javax.swing.JPanel ProductPanel2;
    private javax.swing.JPanel ProductPanel3;
    private javax.swing.JPanel ProductPanel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    
}
